version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /plugins/hanlp_restful_java
    schedule:
      interval: daily
